[theme]
name = "Adwaita Dark"

[theme.base]
white = "#ABB2BF"
black = "#1d1d1d"
grey = "#3E4451"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56B6C2"
magenta = "#C678DD"

[theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#5C6370"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
method = "$blue"
number = "$yellow"
property = "$red"
selfKeyword = "$purple"
string = "$green"
struct = "$yellow"
structure = "$yellow"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
"variable.other.member" = "$red"

[theme.ui]
"activity.background" = "#303030"
"activity.current" = "$black"
"completion.background" = "#242424"
"completion.current" = "#303030"
"editor.background" = "$black"
"editor.caret" = "$white"
"editor.current_line" = "#303030"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.link" = "$cyan"
"editor.selection" = "$grey"
"hover.background" = "#1d1d1d"
"lapce.active_tab" = "#303030"
"lapce.border" = "#454545"
"lapce.dropdown_shadow" = "#"
"lapce.error" = "$red"
"lapce.inactive_tab" = "$grey"
"lapce.scroll_bar" = "#303030"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#242424"
"palette.current" = "#303030"
"panel.background" = "#242424"
"panel.current" = "#303030"
"panel.hovered" = "#454545"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#303030"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 14
header-height = 35
status-height = 25
tab-min-width = 100
activity-width = 50
scroll-width = 10
drop-shadow-width = 0
