name = "lapce-adwaita"
display-name = "Adwaita"
description = "Lapce adaptation of the Adwaita color scheme"
version = "0.1.0"
author = "Kirottu"
repository = "Kirottu/lapce-adwaita"
themes = ["adwaita-dark.toml"]
